Feature/update delete transcation
MasumaJaffery/Vet-Clinic pull request #2
Opened 2023-08-30 21:03 UTC by MasumaJaffery

Hello Code Reviewer,
Hope you are doing Great!
In this Milestone:
1. Update Table.
2. Delete Query Operation.
3. Transactions.
Thanks for reviewing my PR. 🤓 
Stay Blessed! ⭐

2023-08-30 21:24 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @MasumaJaffery , |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
|  <img src="https://media4.giphy.com/media/gfsQffBnuc6e096brx/giphy.gif"/> |

## Highlights

- [ ].. ✅ Greate readme file
- [ ].. ✅ Good commit messages 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-30 21:24 UTC, joskalenda commented on data.sql
> +-- Animal:Boarmon
- [ ] Please make sure you use the correct weight_kg values as per the requirement, I think you used positive numbers instead of negatives ones

2023-08-30 21:28 UTC, MasumaJaffery commented
@joskalenda Sir if negative weight multiple by -1 it turns into positive numbers.
Like 
-1 × -1 = 1

2023-08-31 00:08 UTC, AbayomiOlaoye requested changes
## STATUS: CHANGE REQUIRED ♻️ 

Hi @MasumaJaffery :+1: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so_close](https://camo.githubusercontent.com/0c690ab997907a8c79afe7e695c891f6398cdbef93eaf8ce19f652ff321b54f8/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f744b797263304e546c4563475764546870342f67697068792e676966)


 ## Highlights
- Good PR message ✅ 
- Great commit messages ✅ 
- No linter error ✅ 
- Good reasoning :heavy_check_mark: 

 ## Required Changes ♻️
- [ ] _Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-31 00:08 UTC, AbayomiOlaoye commented on data.sql
> +-- Animal:Boarmon
- [ ] Hi @MasumaJaffery :wave: You seem really good with Maths and that's impressive! I am certain that you will opportunities where that will be greatly useful but you see, for now, according to my colleague @joskalenda, the project requirement was clear to use the values you were given without any expected counter-multiplication or reverse-engineering. Kindly check the requirement attached below and find that there was no additional information on multiplying with a negative value to convert it to positive values:

![image](https://github.com/MasumaJaffery/Vet-Clinic/assets/99715640/9b921c7b-7724-41a6-a2e3-737623d7809d)

Kindly use the figures as seen :pray:

2023-08-31 16:22 UTC, frank1738 approved these changes
Hi @MasumaJaffery , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/tIeCLkB8geYtW/giphy.gif"/>

## Highlights

✅ Good work making the changes requested 👍 


## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-31 16:27 UTC, merged